<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsPackable>true</IsPackable>
        <PackageId>CompositionMaterial.Avalonia</PackageId>
        <Authors>HelloWRC</Authors>
        <Copyright>Copyright (c) 2026 HelloWRC</Copyright>
        <Description>WinUI Composition backed, shape-clipped materials for Avalonia.</Description>
        <PackageTags>avalonia;composition;acrylic;mica;reveal;material</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/HelloWRC/CompositionMaterial.Avalonia</PackageProjectUrl>
        <RepositoryUrl>https://github.com/HelloWRC/CompositionMaterial.Avalonia</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <Version>1.0.1</Version>
        <NoWarn>$(NoWarn);CS1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="[12.1.1]" />
        <PackageReference Include="Avalonia.Win32" Version="[12.1.1]" />
        <PackageReference Include="Avalonia.Skia" Version="[12.1.1]" />
        <PackageReference Include="MicroCom.Runtime" Version="[0.11.6]" />
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
        <TrimmerRootDescriptor Include="ILLink.Descriptors.xml" />
        <None Include="ILLink.Descriptors.xml" Pack="true" PackagePath="buildTransitive/CompositionMaterial.Avalonia.ILLink.Descriptors.xml" />
        <None Include="buildTransitive\CompositionMaterial.Avalonia.targets" Pack="true" PackagePath="buildTransitive/CompositionMaterial.Avalonia.targets" />
        <None Include="..\README.md" Pack="true" PackagePath="README.md" />
    </ItemGroup>

</Project>
